name: publish_conda

on: [push]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: create-recipe
      run: |
        export PATH=$CONDA/bin:$PATH
        conda create -n upload -y python=3.8
        source activate upload
        conda install -c conda-forge grayskull -y
        conda install -y anaconda-client conda-build
        grayskull pypi --strict-conda-forge reservoirpy
        conda-build reservoirpy
        anaconda upload /usr/share/miniconda/envs/upload/conda-bld/noarch/reservoirpy-0.3.6-py_0.tar.bz2 -u fbessou -t fb-59247e4b-bd74-4d3f-b69c-8090f161b6ec



