name: publish_conda

on: [push]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: create-recipe
      run: |
        export PATH=$CONDA/bin:$PATH
        conda create -n upload -y python=3.8
        source activate upload
        conda install -c conda-forge grayskull -y
        conda install -y anaconda-client conda-build
        grayskull pypi --strict-conda-forge reservoirpy
        conda config --set anaconda_upload yes
        conda-build reservoirpy --token fb-7b0c021e-05f6-4487-aea0-b423ba3d7e41 --user fbessou



