name: publish_conda

on: [push]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: activate-conda
      run: conda init
    - name: install-grayskull
      run: conda install -c conda-forge grayskull -y
    - name: gen-recipe
      run: grayskull pypi --strict-conda-forge reservoirpy

