name: publish_conda

on: [push]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: show-miniconda
      run: echo $CONDA
    - name: install-grayskull
      run: $CONDA/bin/conda install -c conda-forge grayskull -y
    - name: gen-recipe
      run: grayskull pypi --strict-conda-forge reservoirpy

