name: publish_conda

on: [push]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: create-recipe
      run: |
        export PATH=$CONDA/bin:$PATH
        conda create -n upload -y python=3.8
        source activate upload
        conda install -c conda-forge grayskull -y
        grayskull pypi --strict-conda-forge reservoirpy


