name: publish_conda

on: [push]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: show-miniconda
      run: echo $CONDA
    - name: install-grayskull
      run: $CONDA install -c conda-forge grayskull

