name: publish_conda

on: [push]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: activate-conda
      run: |
      export PATH=$CONDA/bin:$PATH
      conda create -n upload -y python=3.8
      source activate upload
    - name: install-grayskull
      run: conda install -c conda-forge grayskull -y
    - name: gen-recipe
      run: grayskull pypi --strict-conda-forge reservoirpy

